game:
  arch: win64
  exe: /home/enzo/Downloads/AssettoCorsa.exe
  prefix: ~/Dados/SteamLibrary/steamapps/compatdata/244210/pfx
system:
  disable_runtime: false
  prefer_system_libs: true
  prefix_command: DRI_PRIME=1 mangohud
  reset_desktop: false
wine:
  esync: true
  fsync: true
  system_winetricks: false
  version: lutris-6.10-3-x86_64
  x360ce-dinput: true
