game:
  exe: /home/enzo/Dados/Games-Win/Games/steamapps/common/BeamNG.drive/BeamNG.drive.exe
  prefix: ~/Dados/SteamLibrary/steamapps/compatdata/284160/pfx
system:
  aco: true
  disable_compositor: true
  disable_runtime: true
  gamemode: true
  prefer_system_libs: false
  prefix_command: DRI_PRIME=1 mangohud
wine:
  dxvk_version: v1.7.3L-03f11ba
  esync: true
  fsync: true
  system_winetricks: true
  version: lutris-6.4-x86_64
