game:
  arch: win64
  exe: drive_c/Program Files (x86)/Battle.net/Battle.net.exe
  prefix: /home/enzo/Dados/Games/battlenet
system:
  env:
    DXVK_CONFIG_FILE: /home/enzo/Dados/Games/battlenet/dxvk.conf
    DXVK_STATE_CACHE_PATH: /home/enzo/Dados/Games/battlenet
    STAGING_SHARED_MEMORY: '1'
    __GL_SHADER_DISK_CACHE: '1'
    __GL_SHADER_DISK_CACHE_PATH: /home/enzo/Dados/Games/battlenet
  exclude_processes: Agent.exe "Battle.net Helper.exe"
  manual_command: /home/enzo/Dados/Games/battlenet/state-cache-merge/state-cache-update.sh
wine:
  dxvk: true
  esync: true
  overrides:
    nvapi: disabled
    nvapi64: disabled
  version: lutris-5.7-7-x86_64
