game:
  exe: /home/enzo/Dados/Games/Driver - San Francisco/Driver.exe
  prefix: ~/Dados/wine-prefixes/driver-sa
  working_dir: ~/Dados/Games/Driver - San Francisco
system:
  disable_screen_saver: true
  dri_prime: true
  env:
    DXVK_HUD: '1'
    MANGOHUD: '1'
  gamemode: true
  mangohud: ''
  prefix_command: mangohud
  pulse_latency: true
  vk_icd: ''
wine:
  dxvk_version: v1.9.1L
  esync: true
  fsync: true
