game:
  exe: /home/enzo/Dados/Games/guild-wars-2/drive_c/Program Files/Guild Wars 2/GW2-64.exe
  prefix: ~/Dados/Games/guild-wars-2
system:
  disable_compositor: false
  disable_runtime: true
  gamemode: false
  prefix_command: env DRI_PRIME=1
  single_cpu: true
wine: {}
